version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finstar
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py loaddata data.json
      && python manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db
