# Generated by Django 3.2.13 on 2022-06-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finstar_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number_receipt',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finstar_task.shop', verbose_name='Магазин'),
        ),
    ]
