# Generated by Django 3.2.13 on 2022-06-27 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finstar_task', '0002_alter_receipt_time_issuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_issuance',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
