# Generated by Django 3.2.13 on 2022-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finstar_task', '0002_auto_20220624_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Магазин'),
        ),
    ]
