# Generated by Django 3.2 on 2022-06-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finstar_task', '0003_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='finstar_task.receipt'),
        ),
    ]
